name: automação séries  


on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.3.0
          
      - name: set up pandoc
        uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install dependencies
        run: |
          sudo apt install libcurl4-openssl-dev
          R -e 'install.packages("yfR")'
          R -e 'install.packages("scales")'
          R -e 'install.packages("blastula")'
          R -e 'install.packages("rugarch")'
          R -e 'install.packages("data.table")'
          R -e 'install.packages("forecast")'
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("xts")'
          R -e 'install.packages("quantmode")'
          R -e 'install.packages("ggplot2")'
          R -e 'install.packages("shiny")'
          R -e 'install.packages("tseries")'
          R -e 'install.packages("FinTS")'
          R -e 'install.packages("zoo")'
          R -e 'install.packages("fBasics")'
          R -e 'install.packages("mailtoR")'
          R -e 'install.packages("plotly")'

      # Run Rscript    
      - name: exercutor
        run: |
          Rscript V187939.rproj
          
        # Add new files in folders and commit
      - name: Commit
        run: |
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          git add --all
          git commit -am "add Data"
          git push "https://${{ secrets.REPO_TOKEN }}@github.com/victorkemparski/ME607.git"
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          username: github-actions
          
